# Generated by Django 2.2.25 on 2025-03-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(blank=True, help_text='title', max_length=255, null=True, verbose_name='title ')),
                ('content', models.TextField(blank=True, help_text='content', null=True, verbose_name='content ')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='Creation time', null=True, verbose_name='Creation time')),
                ('user_id', models.IntegerField(blank=True, help_text='Publisher', null=True, verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'Website Announcement',
                'verbose_name_plural': 'Website Announcement',
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(help_text='Permission Name', max_length=255, null=True, verbose_name='Permission Name')),
                ('path', models.CharField(help_text='path', max_length=255, null=True, verbose_name='path')),
                ('orders', models.IntegerField(blank=True, help_text='Order', null=True, verbose_name='Order')),
                ('icon', models.CharField(help_text='icon', max_length=255, null=True, verbose_name='icon')),
                ('page', models.CharField(help_text='Page Path', max_length=255, null=True, verbose_name='Page Path')),
                ('auth', models.CharField(help_text='Permissions', max_length=255, null=True, verbose_name='Permissions')),
                ('p_id', models.IntegerField(blank=True, help_text='Parent ID', null=True, verbose_name='Parent ID')),
                ('deleted', models.IntegerField(blank=True, default=0, help_text='Logical deletion', null=True, verbose_name='Logical deletion')),
                ('type', models.IntegerField(blank=True, help_text='type', null=True, verbose_name='type')),
                ('hide', models.BooleanField(blank=True, help_text='Is it hidden', null=True, verbose_name='Is it hidden')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='Creation time', null=True, verbose_name='Creation time')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='Modification time', null=True, verbose_name='Modification time')),
            ],
            options={
                'verbose_name': 'Permissions',
                'verbose_name_plural': 'Permissions',
                'db_table': 'sys_permission',
            },
        ),
        migrations.CreateModel(
            name='SysDict',
            fields=[
                ('id', models.AutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('code', models.CharField(help_text='coding', max_length=255, verbose_name='coding')),
                ('value', models.CharField(help_text='content', max_length=255, null=True, verbose_name='content')),
                ('type', models.CharField(help_text='type', max_length=10, null=True, verbose_name='type')),
                ('deleted', models.IntegerField(blank=True, default=0, help_text='Logical deletion', null=True, verbose_name='Logical deletion')),
            ],
            options={
                'verbose_name': 'Data dictionary table',
                'verbose_name_plural': 'Data dictionary table',
                'db_table': 'dict',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('username', models.CharField(db_index=True, help_text='username', max_length=255, verbose_name='username')),
                ('password', models.CharField(blank=True, help_text='password', max_length=255, null=True, verbose_name='password')),
                ('name', models.CharField(blank=True, help_text='Nick name', max_length=255, null=True, verbose_name='Nick name')),
                ('email', models.EmailField(blank=True, help_text='Mail', max_length=255, null=True, verbose_name='Mail')),
                ('address', models.CharField(blank=True, help_text='address', max_length=255, null=True, verbose_name='address')),
                ('avatar', models.CharField(blank=True, help_text='avatar', max_length=255, null=True, verbose_name='avatar')),
                ('uid', models.CharField(blank=True, help_text='User unique id', max_length=100, null=True, verbose_name='User unique id')),
                ('role', models.CharField(blank=True, help_text='Role', max_length=255, null=True, verbose_name='Role')),
                ('deleted', models.IntegerField(blank=True, default=0, help_text='Logical deletion', null=True, verbose_name='Logical deletion')),
                ('score', models.IntegerField(blank=True, default=0, help_text='integral', null=True, verbose_name='integral')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='Creation time', null=True, verbose_name='Creation time')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='Modification time', null=True, verbose_name='Modification time')),
            ],
            options={
                'verbose_name': 'User Table',
                'verbose_name_plural': 'User Table',
                'db_table': 'sys_user',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(help_text='Role Name', max_length=255, verbose_name='Role Name')),
                ('flag', models.CharField(help_text='Unique ID', max_length=255, verbose_name='Unique ID')),
                ('deleted', models.IntegerField(blank=True, default=0, help_text='Logical deletion', null=True, verbose_name='Logical deletion')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='Creation time', null=True, verbose_name='Creation time')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='Modification time', null=True, verbose_name='Modification time')),
                ('permission', models.ManyToManyField(to='system.Permission')),
            ],
            options={
                'verbose_name': 'Role List',
                'verbose_name_plural': 'Role List',
                'db_table': 'sys_role',
            },
        ),
    ]
